---
name: lint
on:
  push:

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Validate OpenAPI
        uses: docker://github/super-linter:v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_OPENAPI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  spectral-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npx @stoplight/spectral-cli lint ./ipfs-pinning-service.yaml
